---
name: "CI"
on:  # yamllint disable
  - "push"
  - "pull_request"
jobs:
  yamllint:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      # - name: "Set up Python"
      #   uses: "actions/setup-python@v2"
      #   id: "python-setup"
      #   with:
      #     python-version: "3.10"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
      - name: "Linting: yamllint"
        run: "poetry run invoke yamllint"
