---
name: "CI"
on:  # yamllint disable
  - "pull_request"
jobs:
  yamllint:
    runs-on: "ubuntu-20.04"
    env:
      INVOKE_NAUTOBOT_DOCKER_COMPOSE_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
      - name: "Linting: yamllint"
        run: "poetry run invoke yamllint"
  # unittest:
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       # python-version: ["3.10"]
  #       # db-backend: ["postgresql"]
  #       # nautobot-version: ["stable"]
  #       include:
  #         - python-version: "3.10"
  #           db-backend: "postgresql"
  #           nautobot-version: "2.3.2"
  #         # - python-version: "3.12"
  #         #   db-backend: "mysql"
  #         #   nautobot-version: "stable"
  #   runs-on: "ubuntu-22.04"
  #   env:
  #     INVOKE_NAUTOBOT_DOCKER_COMPOSE_PYTHON_VER: "${{ matrix.python-version }}"
  #     INVOKE_NAUTOBOT_DOCKER_COMPOSE_NAUTOBOT_VER: "${{ matrix.nautobot-version }}"
  #   steps:
  #     - name: "Check out repository code"
  #       uses: "actions/checkout@v4"
  #     - name: "Setup environment"
  #       uses: "networktocode/gh-action-setup-poetry-environment@v6"
  #     - name: "Copy credentials"
  #       run: "cp environments/creds.example.env environments/creds.env"
  #     - name: "Copy local ENV vars"
  #       run: "cp environments/local.example.env environments/local.env"
  #     - name: "Constrain Nautobot version and regenerate lock file"
  #       env:
  #         INVOKE_NAUTOBOT_DEVICE_ONBOARDING_LOCAL: "true"
  #       run: "poetry run invoke lock --constrain-nautobot-ver --constrain-python-ver"
  #     - name: "Set up Docker Buildx"
  #       id: "buildx"
  #       uses: "docker/setup-buildx-action@v3"
  #     - name: "Build"
  #       uses: "docker/build-push-action@v5"
  #       with:
  #         builder: "${{ steps.buildx.outputs.name }}"
  #         context: "./"
  #         push: false
  #         load: true
  #         file: "./environments/Dockerfile"
  #         cache-from: "type=gha,scope=${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
  #         cache-to: "type=gha,scope=${{ matrix.nautobot-version }}-py${{ matrix.python-version }}"
  #         build-args: |
  #           NAUTOBOT_VER=${{ matrix.nautobot-version }}
  #           PYTHON_VER=${{ matrix.python-version }}
  #           CI=true
  #     - name: "Run Tests"
  #       run: "poetry run invoke unittest"
  sync_jobs_repo:
    runs-on: "ubuntu-20.04"
    env:
      INVOKE_NAUTOBOT_DOCKER_COMPOSE_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v6"
      - name: "Sync Jobs Repo"
        run: "poetry run python sync_jobs_repo.py"